### ISSUE TITLE
Catch "divide by zero" error in Customer Sales Report

### ISSUE THREAD

**Issue by dfrankland** [rfhk/cip-custom#6] opened 2015-01-16 18:46 UTC
When exporting the Customer Sales Report during January of the current year (no current year average), `customer_sales_report.py` throws an "Unexpected end of input" error. This is due to dividing by zero here: https://github.com/rfhk/cip-customization/blob/master/account_customer_sales_report/report/customer_sales_report.py#L165

Please make sure to throw an error that says reporting the current year is not possible until January ends to make it clear there is no server error.

Here is the error log:

```
2015-01-16 18:14:07,390 6944 ERROR PCI-TEST openerp.addons.report_aeroo.report_aeroo: Report generation error!
Traceback (most recent call last):
  File "/opt/openerp/addons/cip-customization/report_aeroo/report_aeroo.py", line 449, in create_aeroo_report
    data = basic.generate(**oo_parser.localcontext).render().getvalue()
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/base.py", line 51, in render
    return self.serializer(self.events)
  File "/usr/local/lib/python2.7/dist-packages/aeroolib-1.2.0-py2.7.egg/aeroolib/plugins/opendocument.py", line 1209, in __call__
    for kind, data, pos in stream:
  File "/usr/lib/python2.7/dist-packages/genshi/template/base.py", line 618, in _include
    for event in stream:
  File "/usr/lib/python2.7/dist-packages/genshi/template/markup.py", line 326, in _match
    for event in stream:
  File "/usr/lib/python2.7/dist-packages/genshi/template/base.py", line 558, in _flatten
    for kind, data, pos in stream:
  File "/usr/lib/python2.7/dist-packages/genshi/template/directives.py", line 360, in __call__
    iterable = _eval_expr(self.expr, ctxt, vars)
  File "/usr/lib/python2.7/dist-packages/genshi/template/base.py", line 289, in _eval_expr
    retval = expr.evaluate(ctxt)
  File "/usr/lib/python2.7/dist-packages/genshi/template/eval.py", line 178, in evaluate
    return eval(self.code, _globals, {'__data__': data})
  File "<string>", line 1, in <Expression u'iter(print_sales(data))'>
  File "/opt/openerp/addons/cip-customization/account_customer_sales_report/report/customer_sales_report.py", line 241, in print_sales
    lines = self._get_lines(cr, uid, sales_data, period_ids, year_id, eff_periods, context=None)
  File "/opt/openerp/addons/cip-customization/account_customer_sales_report/report/customer_sales_report.py", line 165, in _get_lines
    line_vals[i]['ratio'] = line_vals[i]['avg_curr_year'] / line_vals[i]['avg_prev_year']
ZeroDivisionError: float division by zero

2015-01-16 18:14:07,391 6944 ERROR PCI-TEST openerp.service.web_services: Exception: (u'Aeroo Reports: Error while generating the report "Customer Sales".', ZeroDivisionError('float division by zero',))
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/service/web_services.py", line 712, in go
    (result, format) = obj.create(cr, uid, ids, datas, context)
  File "/opt/openerp/addons/cip-customization/report_aeroo/report_aeroo.py", line 724, in create
    return fnct(cr, uid, ids, data, report_xml, context)
  File "/opt/openerp/addons/cip-customization/report_aeroo/report_aeroo.py", line 667, in create_source_odt
    return self.create_single_pdf(cr, uid, ids, data, report_xml, context)
  File "/opt/openerp/addons/cip-customization/report_aeroo/report_aeroo.py", line 507, in create_single_pdf
    return self.create_aeroo_report(cr, uid, ids, data, report_xml, context=context, output=output)
  File "/opt/openerp/addons/cip-customization/report_aeroo/report_aeroo.py", line 458, in create_aeroo_report
    raise osv.except_osv(_('Aeroo Reports: Error while generating the report "%s".') % report_xml.name, e)
except_osv: (u'Aeroo Reports: Error while generating the report "Customer Sales".', ZeroDivisionError('float division by zero',))
2015-01-16 18:14:07,560 6944 ERROR PCI-TEST openerp.netsvc: Aeroo Reports: Error while generating the report "Customer Sales".
float division by zero
Traceback (most recent call last):
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 654, in dispatch
    res = fn(db, uid, *params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 760, in exp_report_get
    return self._check_report(report_id)
  File "/opt/openerp/server/openerp/service/web_services.py", line 738, in _check_report
    netsvc.abort_response(exc, exc.message, 'warning', exc.traceback)
  File "/opt/openerp/server/openerp/netsvc.py", line 71, in abort_response
    raise openerp.osv.osv.except_osv(description, details)
except_osv: (u'Aeroo Reports: Error while generating the report "Customer Sales".', u'float division by zero')
```

**Comment by yostashiro** [comment] 2015-01-18 10:20
Thanks for the report.  I have updated the code to handle the reported case, which happens when there are sales records from previous year for a customer but the total for the customer ended up being zero due to return, etc.

You can find the change here: https://github.com/rfhk/cip-customization/commit/ce01ffcb32ca2e90009ec80047c8502862db3930
(Please disregard the changes on the other file - I just commented out some unused parts.)

If I understand the issue correctly, it has nothing to do with the current period being January and the report should still run and show results even before January ends.

What I wasn't sure was if the error message I got from Ogawa-san below was coming from the same cause.

> OpenERP Client error
> Uncaught SyntaxError: Unexpected end of input
> http://(host)/?db=(DB)#page=0&limit=80&view_type=list&model=account.invoice&menu_id=222&action=246:0
)

In my development environment, I was getting this error, which appeared different to above.
![_011815_045945_pm](https://cloud.githubusercontent.com/assets/7766939/5792028/cc86b2fa-9f3d-11e4-9c32-2fd7f6b62df2.jpg)

Anyway, hope the issue is fixed with this update.  Thank you very much for your help.

**Closed** 2017-08-18 03:10 UTC
